### ISSUE TITLE
breaks on empty content items

### ISSUE THREAD

**Issue by raoel** [BramVer/cson-to-markdown#1]
Thank you for this! I used it for the same purpose (export of Boostnote files).

I found an issue, if you care:
if the `content '''` is empty it will break on that file.

also, for some reason I had multiple cson files with `content ""` (also empty, but with double quotes).

I worked around this by deleting the failing .cson files

**Comment by BramVer** [comment]
Thanks for the ticket, I'm glad this little thing's also helpful for others.  
I'll look into it tonight, should be a small fix :)

**Comment by BramVer** [comment]
I made it skip files where it cannot find the Markdown boundary markers:  
`content '''` and `'''`.
But I could not make it crash when the content itself was just empty:  
 ```
content '''
'''
```

Can you provide a stacktrace?

**Comment by raoel** [comment]
hm, I deleted those file. I tried to restore them, but didn't succeed :-(

I guess it's a "cannot reproduce" then. 
If I remember correctly everything that failed contained this data:
```
isTrashed: true
```

**Comment by BramVer** [comment]
I bumped the version to 0.1.3 with the minor fix included.  
Should work for you now :)

**Comment by BramVer** [comment]
Closing for now.
